[layout]
finger_assignment = [
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [0, 0, 0, 0, 5, 5, 6, 6, 0, 0, 0, 0],
]

finger_effort = [
  [5.0, 3.0, 2.0, 1.0, 2.0, 7.0, 7.0, 2.0, 1.0, 2.0, 3.0, 5.0],
  [5.0, 1.0, 1.0, 1.0, 1.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0, 5.0],
  [7.0, 3.0, 2.0, 2.0, 1.0, 8.0, 8.0, 1.0, 2.0, 2.0, 3.0, 7.0],
  [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
]

key_size = [1.0, 1.0]

key_centers = [
  [[0.0, 0.0], [0.0, 1.0], [0.0, 2.0], [0.0, 3.0], [0.0, 4.0], [0.0, 5.0], [0.0, 6.0], [0.0, 7.0], [0.0, 8.0], [0.0, 9.0], [0.0, 10.0], [0.0, 11.0]],
  [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0], [1.0, 10.0], [1.0, 11.0]],
  [[2.0, 0.0], [2.0, 1.0], [2.0, 2.0], [2.0, 3.0], [2.0, 4.0], [2.0, 5.0], [2.0, 6.0], [2.0, 7.0], [2.0, 8.0], [2.0, 9.0], [2.0, 10.0], [2.0, 11.0]],
  [[3.0, 0.0], [3.0, 1.0], [3.0, 2.0], [3.0, 3.0], [3.0, 4.0], [3.0, 5.0], [3.0, 6.0], [3.0, 7.0], [3.0, 8.0], [3.0, 9.0], [3.0, 10.0], [3.0, 11.0]],
]

finger_home_positions.1 = [1, 1]
finger_home_positions.2 = [1, 2]
finger_home_positions.3 = [1, 3]
finger_home_positions.4 = [1, 4]
finger_home_positions.5 = [3, 4]
finger_home_positions.6 = [3, 7]
finger_home_positions.7 = [1, 7]
finger_home_positions.8 = [1, 8]
finger_home_positions.9 = [1, 9]
finger_home_positions.10 = [1, 10]

[optimization.simulated_annealing]
init_temp = 150.0
cooling = 0.998
key_switches = 2
stall_accepted = 5000

# The scales are calculated against all cyanophage layouts, using english and italian corpuses. For reference, see branch "feat/generate-optimization-targets"
[optimization.targets]
effort = { value = 0.0, weight = 1.0, scale = 21.163663564565567 }
pinky_off_home = { value = 0.0, weight = 1.0, scale = 1.6227459939519908 }
left_hand_usage = { value = 50.0, weight = 1.0, scale = 3.4762457706965426 }
bigram_skips_1 = { value = 0.0, weight = 1.0, scale = 0.5834702593515358 }
bigram_skips_n = { value = 0.0, weight = 1.0, scale = 0.26056074861659523 }
bigram_scissors = { value = 0.0, weight = 1.0, scale = 1.8775387876827239 }
bigram_scissors_wide = { value = 0.0, weight = 1.0, scale = 2.780006834651852 }
bigram_lateral_stretches = { value = 0.0, weight = 1.0, scale = 0.8842516320921315 }
trigram_skips_1_same_hand = { value = 0.0, weight = 1.0, scale = 0.4825378205048694 }
trigram_skips_1_alternation = { value = 0.0, weight = 1.0, scale = 0.5968208489429571 }
trigram_skips_n_same_hand = { value = 0.0, weight = 1.0, scale = 0.12917178590308467 }
trigram_skips_n_alternation = { value = 0.0, weight = 1.0, scale = 0.19807365424094808 }
trigram_scissors_same_hand = { value = 0.0, weight = 1.0, scale = 0.4321853345684053 }
trigram_scissors_alternation = { value = 0.0, weight = 1.0, scale = 1.149318148266971 }
trigram_scissors_wide_same_hand = { value = 0.0, weight = 1.0, scale = 0.6526245529286203 }
trigram_scissors_wide_alternation = { value = 0.0, weight = 1.0, scale = 1.3566996093907533 }
trigram_lateral_stretches_same_hand = { value = 0.0, weight = 1.0, scale = 0.1722023846308773 }
trigram_lateral_stretches_alternation = { value = 0.0, weight = 1.0, scale = 0.5670775326487517 }
trigram_redirects_strong = { value = 0.0, weight = 1.0, scale = 0.473299496390173 }
trigram_redirects_weak = { value = 0.0, weight = 1.0, scale = 1.1889935758498835 }
trigram_roll_ratio = { value = 100.0, weight = 1.0, scale = 24.016393264558403 }
trigram_roll_ratio_bigrams = { value = 100.0, weight = 1.0, scale = 12.037637961648924 }
trigram_alternations = { value = 25.0, weight = 1.0, scale = 3.46520215110393 }
