[layout]
finger_assignment = [
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10],
  [0, 0, 0, 0, 5, 5, 6, 6, 0, 0, 0, 0],
]

finger_effort = [
  [5.0, 3.0, 2.0, 1.0, 2.0, 7.0, 7.0, 2.0, 1.0, 2.0, 3.0, 5.0],
  [5.0, 1.0, 1.0, 1.0, 1.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0, 5.0],
  [7.0, 3.0, 2.0, 2.0, 1.0, 8.0, 8.0, 1.0, 2.0, 2.0, 3.0, 7.0],
  [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
]

[layout.finger_home_positions]
1 = [1, 1]
2 = [1, 2]
3 = [1, 3]
4 = [1, 4]
5 = [3, 4]
6 = [3, 7]
7 = [1, 7]
8 = [1, 8]
9 = [1, 9]
10 = [1, 10]

[optimization]
algorithm = "simulated_annealing"

[optimization.simulated_annealing]
init_temp = 150.0
cooling = 0.998
key_switches = 2
stall_accepted = 5000

[optimization.targets]
effort = { value = 0.0, weight = 1.0, scale = 50.0 }
pinky_off_home = { value = 0.0, weight = 1.0, scale = 1.0 }
left_hand_usage = { value = 50.0, weight = 1.0, scale = 8.0 }
bigram_skips_1 = { value = 0.0, weight = 1.0, scale = 1.0 }
bigram_skips_n = { value = 0.0, weight = 1.0, scale = 1.0 }
bigram_lateral_stretches = { value = 0.0, weight = 1.0, scale = 1.0 }
bigram_scissors = { value = 0.0, weight = 1.0, scale = 2.0 }
bigram_wide_scissors = { value = 0.0, weight = 1.0, scale = 1.0 }
trigram_skips_same_hand = { value = 0.0, weight = 1.0, scale = 1.0 }
trigram_skips_alternation = { value = 0.0, weight = 1.0, scale = 1.0 }
trigram_roll_ratio = { value = 50.0, weight = 1.0, scale = 15.0 }
trigram_redirects_weak = { value = 0.0, weight = 1.0, scale = 1.0 }
trigram_redirects_strong = { value = 0.0, weight = 1.0, scale = 1.0 }
trigram_alternations = { value = 100.0, weight = 1.0, scale = 8.0 }
