layout:
  finger_assignment:
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [1, 1, 2, 3, 4, 4, 7, 7, 8, 9, 10, 10]
    - [0, 0, 0, 0, 5, 5, 6, 6, 0, 0, 0, 0]

  finger_effort:
    - [5.0, 3.0, 2.0, 1.0, 2.0, 7.0, 7.0, 2.0, 1.0, 2.0, 3.0, 5.0]
    - [5.0, 1.0, 1.0, 1.0, 1.0, 5.0, 5.0, 1.0, 1.0, 1.0, 1.0, 5.0]
    - [7.0, 3.0, 2.0, 2.0, 1.0, 8.0, 8.0, 1.0, 2.0, 2.0, 3.0, 7.0]
    - [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]

  key_size: [1.0, 1.0]

  key_centers:
    - [[0.0, 0.0], [0.0, 1.0], [0.0, 2.0], [0.0, 3.0], [0.0, 4.0], [0.0, 5.0], [0.0, 6.0], [0.0, 7.0], [0.0, 8.0], [0.0, 9.0], [0.0, 10.0], [0.0, 11.0]]
    - [[1.0, 0.0], [1.0, 1.0], [1.0, 2.0], [1.0, 3.0], [1.0, 4.0], [1.0, 5.0], [1.0, 6.0], [1.0, 7.0], [1.0, 8.0], [1.0, 9.0], [1.0, 10.0], [1.0, 11.0]]
    - [[2.0, 0.0], [2.0, 1.0], [2.0, 2.0], [2.0, 3.0], [2.0, 4.0], [2.0, 5.0], [2.0, 6.0], [2.0, 7.0], [2.0, 8.0], [2.0, 9.0], [2.0, 10.0], [2.0, 11.0]]
    - [[3.0, 0.0], [3.0, 1.0], [3.0, 2.0], [3.0, 3.0], [3.0, 4.0], [3.0, 5.0], [3.0, 6.0], [3.0, 7.0], [3.0, 8.0], [3.0, 9.0], [3.0, 10.0], [3.0, 11.0]]

  finger_home_positions:
    1: [1, 1]
    2: [1, 2]
    3: [1, 3]
    4: [1, 4]
    5: [3, 4]
    6: [3, 7]
    7: [1, 7]
    8: [1, 8]
    9: [1, 9]
    10: [1, 10]

optimization:
  simulated_annealing:
    init_temp: 150.0
    cooling: 0.998
    key_switches: 2
    stall_accepted: 5000

  targets:
    effort:
      value: 130.0
      weight: 1.0
      scale: 21.24262
    pinky_off_home:
      value: 0.0
      weight: 1.0
      scale: 1.62879
    left_hand_usage:
      value: 0.0
      weight: 1.0
      scale: 3.47625

    finger_usage:
      value: {}
      weight:
        left_pinky: 1.0
        left_ring: 1.0
        left_middle: 1.0
        left_index: 1.0
        left_thumb: 1.0
        right_pinky: 1.0
        right_ring: 1.0
        right_middle: 1.0
        right_index: 1.0
        right_thumb: 1.0
      scale:
        left_pinky: 1.93042
        left_ring: 1.58781
        left_middle: 3.08803
        left_index: 2.42221
        left_thumb: 3.98635
        right_pinky: 2.47639
        right_ring: 2.60017
        right_middle: 3.20679
        right_index: 3.13865
        right_thumb: 1.52169

    row_usage:
      value: {}
      weight:
        0: 1.0
        1: 1.0
        2: 1.0
        3: 1.0
      scale:
        0: 6.68443
        1: 6.11374
        2: 4.64896
        3: 4.0908

    column_usage:
      value: {}
      weight:
        0: 1.0
        1: 1.0
        2: 1.0
        3: 1.0
        4: 1.0
        5: 1.0
        6: 1.0
        7: 1.0
        8: 1.0
        9: 1.0
        10: 1.0
        11: 1.0
      scale:
        0: 0.18226
        1: 1.97201
        2: 1.58781
        3: 3.08803
        4: 4.18414
        5: 2.22826
        6: 2.02175
        7: 3.85509
        8: 3.20679
        9: 2.60017
        10: 2.59885
        11: 0.3441

    bigram_skips:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.58565
        2: 0.26153

    bigram_scissors:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.92124
        2: 1.158

    bigram_lateral_stretches:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      weight:
        pinky: 1.0
        ring: 1.0
        index: 1.0
      scale:
        pinky: 0.64121
        ring: 0.8588
        index: 0.88234

    trigram_skips_same_hand:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.48434
        2: 0.12965

    trigram_skips_alternation:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.59905
        2: 0.19881

    trigram_scissors_same_hand:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.20181
        2: 0.161

    trigram_scissors_alternation:
      value:
        1: 0.0
        2: 0.0
      weight:
        1: 1.0
        2: 1.0
      scale:
        1: 0.76523
        2: 0.48938

    trigram_lateral_stretches_same_hand:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      weight:
        pinky: 1.0
        ring: 1.0
        index: 1.0
      scale:
        pinky: 0.12323
        ring: 0.10838
        index: 0.16829

    trigram_lateral_stretches_alternation:
      value:
        pinky: 0.0
        ring: 0.0
        index: 0.0
      weight:
        pinky: 1.0
        ring: 1.0
        index: 1.0
      scale:
        pinky: 0.46957
        ring: 0.50452
        index: 0.57239

    trigram_redirects:
      value:
        strong: 0.0
        weak: 0.0
      weight:
        strong: 1.0
        weak: 1.0
      scale:
        strong: 1.477
        weak: 0.19694

    trigram_roll_ratio:
      value: 100.0
      weight: 1.0
      scale: 24.01639
    trigram_roll_ratio_bigrams:
      value: 100.0
      weight: 1.0
      scale: 12.03764
    trigram_alternations:
      value: 25.0
      weight: 1.0
      scale: 3.47812
